/**
 * Seeds the database from seed/catalog.json (generated by scripts/prepare-content.py
 * from the old trumee.in Shopify store). Idempotent: skips if products exist unless --reset.
 *
 *   npm run db:seed            # first-time import
 *   npm run db:seed -- --reset # wipe catalog/content and re-import
 */
import "dotenv/config";
import bcrypt from "bcryptjs";
import { readFileSync } from "node:fs";
import path from "node:path";
import { sql } from "drizzle-orm";
import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";
import * as schema from "../src/db/schema";
import { slugify } from "../src/lib/utils";

const client = postgres(process.env.DATABASE_URL!, { max: 1 });
const db = drizzle(client, { schema });

type Catalog = {
  products: {
    handle: string;
    title: string;
    bodyHtml: string;
    tags: string[];
    createdAt: string;
    publishedAt: string | null;
    options: { name: string; values: string[] }[];
    variants: {
      title: string;
      sku: string | null;
      price: string;
      compareAtPrice: string | null;
      option1: string | null;
      option2: string | null;
      option3: string | null;
      available: boolean;
      grams: number;
    }[];
    images: { url: string; alt: string; width: number; height: number }[];
  }[];
  collections: { handle: string; title: string; descriptionHtml: string; products: string[] }[];
  pages: { handle: string; title: string; bodyHtml: string }[];
  posts: { handle: string; title: string; publishedAt: string; author: string; bodyHtml: string; excerpt: string }[];
  drafts: { handle: string; title: string; productType: string; images: { url: string; alt: string; width: number; height: number }[] }[];
};

const catalog: Catalog = JSON.parse(readFileSync(path.join(__dirname, "..", "seed", "catalog.json"), "utf8"));

const CATEGORY_COLLECTIONS: Record<string, string> = {
  dresses: "Dresses",
  tops: "Tops",
  skirts: "Skirts",
  jumpsuit: "Jumpsuits",
  shirts: "Shirts",
  "co-ord-sets": "Co-ord Sets",
};
const SIZE_ORDER = ["XS", "S", "M", "L", "XL", "2XL", "XXL", "3XL"];
const STARTING_STOCK = 10; // Shopify's public feed only exposes in/out of stock

const paise = (v: string | null) => (v == null ? null : Math.round(parseFloat(v) * 100));
const cleanTag = (t: string) => t.trim().toLowerCase();
const isPriceTag = (t: string) => /^(above|below)\s?\d+$/.test(t);

const EDIT_IMAGES: Record<string, string> = {
  "main-character-energy": "/images/lifestyle/hero-pink-wall.webp",
  "in-her-element": "/images/lifestyle/stone-wall.webp",
  "wander-x-wear": "/images/lifestyle/lake-wide.webp",
  "after-the-rain": "/images/lifestyle/forest-walk.webp",
  "free-spirited": "/images/lifestyle/forest-blue.webp",
  "escape-edit": "/images/lifestyle/lake-rust.webp",
};

const ABOUT_HTML = `
<h2>The future of fashion begins with a question: what if clothing could think?</h2>
<p>What if your dress knew the mood of the season before anyone else? What if your favourite jumpsuit was made only when you needed it — not months before? What if a skirt understood your shape better than the size chart ever could?</p>
<p>Welcome to Trumee — a fashion-tech house where imagination meets infrastructure. We started small — a design-led label creating effortless clothing for escape-seekers and life-lovers. But we began noticing the cracks that every fashion founder sees.</p>
<h3>An expression of self and effortless style</h3>
<p>At Trumee, fashion is about feeling free — in your skin, in your clothes, in the world. We create easygoing, feel-good styles inspired by nature, movement, and the joy of vacation dressing. While we’re not 100% sustainable yet, we care deeply about thoughtful choices — from better fabrics to mindful production. We’re on a journey, just like you.</p>
<h3>Designed for the spirit of getaway</h3>
<p>Adventure is more than travel — it’s a mindset. Trumee clothes are made for spontaneous weekend getaways, barefoot evenings, and stories that start with “why not?” With real-time style insights guiding our collections, you get pieces that feel fresh, easy, and unmistakably you. It’s fashion for your boldest moods and softest days.</p>
<h3>Fashion meets functional magic</h3>
<p>We love great clothes, but we also love smart systems. Trumee blends personal style with tech innovation — from our trend radar and virtual try-ons to community-powered styling and fit intelligence. We’re building tools to make shopping smarter, choices clearer, and your wardrobe truly yours.</p>
<h3>Living for the journey</h3>
<p>Every stitch tells a story. Inspired by vibrant escapes and everyday magic, our collections are crafted to move with you — from seaside strolls to city wanderings. We’re not just creating clothes. We’re crafting a movement — where style meets sense.</p>
<h3>What makes us special</h3>
<ul>
<li><strong>Designed for life’s most meaningful moments.</strong> Clothing that adds a touch of magic to every moment and to your most treasured memories.</li>
<li><strong>Where style meets comfort, effortlessly.</strong> You shouldn’t have to choose between looking great and feeling great.</li>
<li><strong>A celebration of your authentic self.</strong> Pieces meant to empower, inspire, and reflect your unique path.</li>
<li><strong>Timeless, versatile designs for every woman.</strong> Exploring a new city, lounging by the beach, or attending a special event — there’s a Trumee piece for it.</li>
</ul>`;

const FAQ_HTML = `
<h3>General</h3>
<h4>What is Trumee?</h4><p>Trumee is where effortless fashion meets intelligent design — made for women who wander, wonder, and wear their truth. We use technology to solve problems in the fashion value chain.</p>
<h4>Where do you deliver?</h4><p>We deliver to all serviceable pin codes across India. If your location is not serviceable, we will notify you shortly after you place your order.</p>
<h3>Orders & payments</h3>
<h4>How do I place an order?</h4><p>Browse the store, add the pieces you love to your bag and check out. You’ll receive an email/SMS confirming your order.</p>
<h4>Which payment methods do you accept?</h4><p>All major cards, UPI, net banking and wallets through our secure payment partner, plus Cash on Delivery.</p>
<h4>Can I cancel my order?</h4><p>Orders can be cancelled within 24 hours of placement, provided they haven’t been processed for shipping. Once shipped, an order cannot be cancelled.</p>
<h3>Returns, exchanges & refunds</h3>
<h4>How do I start a return or exchange?</h4><p>You can return items within 7 days of delivery. Go to <a href="/account">My Account → Orders</a> and choose “Request return”, or use the <a href="/track-order">order tracking page</a>.</p>
<h4>What are the conditions for returns?</h4><p>Items must be unused, unworn and unwashed with all original tags intact. Items marked “Final Sale” cannot be returned.</p>
<h4>How are refunds processed?</h4><p>Refunds go to the original payment method or as store credit, typically within 7–10 business days after we receive and inspect the item.</p>
<h4>I received a damaged or incorrect item.</h4><p>Tell us within 48 hours of delivery and we’ll arrange a free pickup and a replacement or refund.</p>
<h3>Shipping & delivery</h3>
<h4>How long does delivery take?</h4><p>Metro cities: 2–4 business days · Tier 2 & 3 cities: 3–6 business days · Remote areas: 5–8 business days.</p>
<h4>How can I track my order?</h4><p>You’ll get tracking details by email/SMS once your order ships, or visit <a href="/track-order">Track your order</a>.</p>
<h4>What if delivery fails?</h4><p>The courier will attempt redelivery up to two times. If the package remains undelivered, it is returned to us and the order is cancelled.</p>
<h3>Account & privacy</h3>
<h4>Do I need an account to shop?</h4><p>No — you can check out as a guest. An account lets you track orders, save addresses and keep a wishlist.</p>
<h4>How secure is my information?</h4><p>Payments are processed by PCI-DSS compliant gateways; we never store card details. See our <a href="/pages/privacy-policy">Privacy Policy</a>.</p>`;

async function main() {
  const reset = process.argv.includes("--reset");
  const [{ count }] = await db.select({ count: sql<number>`count(*)::int` }).from(schema.products);
  if (count > 0 && !reset) {
    console.log(`Products already present (${count}). Use --reset to re-import.`);
  } else {
    if (reset) {
      await db.execute(sql`TRUNCATE collection_products, product_images, variants, products, collections, pages, blog_posts, redirects RESTART IDENTITY CASCADE`);
    }
    await importCatalog();
  }
  await attachVideos();
  await applySeoContent();
  await ensureOwner();
  await client.end();
}

/** seed/seo-content.json → collection titles, meta, guides and FAQs. Safe to re-run. */
async function applySeoContent() {
  type Entry = { seoTitle: string; seoDescription: string; intro: string; guideHtml: string; faqs: { q: string; a: string }[] };
  const data: { collections: Record<string, Entry> } = JSON.parse(readFileSync(path.join(__dirname, "..", "seed", "seo-content.json"), "utf8"));
  let n = 0;
  for (const [handle, e] of Object.entries(data.collections)) {
    const res = await db
      .update(schema.collections)
      .set({ seoTitle: e.seoTitle, seoDescription: e.seoDescription, descriptionHtml: `<p>${e.intro}</p>`, guideHtml: e.guideHtml, faqs: e.faqs })
      .where(sql`handle = ${handle}`)
      .returning({ id: schema.collections.id });
    n += res.length;
  }
  console.log(`Applied SEO content to ${n} collections.`);

  // Search-targeted journal guides (upsert by handle)
  type Post = { handle: string; title: string; seoTitle: string; seoDescription: string; excerpt: string; coverUrl: string; tags: string[]; bodyHtml: string };
  const posts: Post[] = JSON.parse(readFileSync(path.join(__dirname, "..", "seed", "posts-seo.json"), "utf8"));
  for (const p of posts) {
    await db
      .insert(schema.blogPosts)
      .values({ ...p, author: "Team Trumee", publishedAt: new Date() })
      .onConflictDoUpdate({ target: schema.blogPosts.handle, set: { title: p.title, seoTitle: p.seoTitle, seoDescription: p.seoDescription, excerpt: p.excerpt, coverUrl: p.coverUrl, tags: p.tags, bodyHtml: p.bodyHtml } });
  }
  console.log(`Upserted ${posts.length} journal guides.`);
}

/** seed/videos.json maps public/videos/<sku>.mp4 → product handle. Safe to re-run. */
async function attachVideos() {
  const map: Record<string, string | null> = JSON.parse(readFileSync(path.join(__dirname, "..", "seed", "videos.json"), "utf8"));
  let n = 0;
  for (const [sku, handle] of Object.entries(map)) {
    if (sku.startsWith("_") || !handle) continue;
    const res = await db
      .update(schema.products)
      .set({ videoUrl: `/videos/${sku}.mp4`, videoPoster: `/videos/${sku}.webp` })
      .where(sql`handle = ${handle}`)
      .returning({ id: schema.products.id });
    if (!res.length) console.warn(`video ${sku}: no product with handle ${handle}`);
    n += res.length;
  }
  console.log(`Attached ${n} product videos.`);
}

async function importCatalog() {
  // Which category does each product belong to? Drives productType.
  const typeByHandle = new Map<string, string>();
  for (const c of catalog.collections) {
    if (CATEGORY_COLLECTIONS[c.handle]) c.products.forEach((h) => typeByHandle.set(h, CATEGORY_COLLECTIONS[c.handle]));
  }

  const idByOldHandle = new Map<string, number>();
  const usedHandles = new Set<string>();
  const redirectRows: { fromPath: string; toPath: string }[] = [];

  for (const p of catalog.products) {
    let handle = slugify(p.title);
    while (usedHandles.has(handle)) handle += "-2";
    usedHandles.add(handle);
    if (handle !== p.handle) redirectRows.push({ fromPath: `/products/${p.handle}`, toPath: `/products/${handle}` });

    const sizeOpt = p.options.find((o) => o.name === "Size");
    if (sizeOpt) sizeOpt.values.sort((a, b) => SIZE_ORDER.indexOf(a) - SIZE_ORDER.indexOf(b));
    const colorOpt = p.options.find((o) => o.name === "Color");
    const options = p.options.filter((o) => !(o.name === "Title" && o.values[0] === "Default Title"));

    const [prod] = await db
      .insert(schema.products)
      .values({
        handle,
        title: p.title,
        descriptionHtml: p.bodyHtml,
        status: "active",
        productType: typeByHandle.get(p.handle) ?? "",
        tags: [...new Set(p.tags.map(cleanTag).filter((t) => !isPriceTag(t)))],
        options,
        fabric: guessFabric(p.title + " " + p.bodyHtml),
        care: "Gentle hand wash in cold water. Dry in shade. Do not bleach. Warm iron on reverse.",
        seoTitle: `${p.title} | Trumee`,
        publishedAt: p.publishedAt ? new Date(p.publishedAt) : new Date(),
        createdAt: new Date(p.createdAt),
      })
      .returning({ id: schema.products.id });
    idByOldHandle.set(p.handle, prod.id);

    await db.insert(schema.productImages).values(
      p.images.map((im, i) => ({ productId: prod.id, url: im.url, alt: im.alt, width: im.width, height: im.height, position: i })),
    );

    const sorted = [...p.variants].sort(
      (a, b) => SIZE_ORDER.indexOf(a.option1 ?? "") - SIZE_ORDER.indexOf(b.option1 ?? ""),
    );
    await db.insert(schema.variants).values(
      sorted.map((v, i) => {
        const price = paise(v.price)!;
        const compare = paise(v.compareAtPrice);
        return {
          productId: prod.id,
          title: v.title,
          sku: v.sku ? `${v.sku}-${v.option1 ?? i}` : null,
          price,
          compareAtPrice: compare && compare > price ? compare : null,
          option1: v.option1,
          option2: colorOpt ? v.option2 : v.option2,
          option3: v.option3,
          inventoryQty: v.available ? STARTING_STOCK : 0,
          weightGrams: v.grams || 300,
          position: i,
        };
      }),
    );
  }

  // Collections (skip Shopify's "home" catch-all; /collections/all replaces it)
  let pos = 0;
  for (const c of catalog.collections) {
    if (c.handle === "home") continue;
    const isCategory = !!CATEGORY_COLLECTIONS[c.handle];
    const first = catalog.products.find((p) => p.handle === c.products[0]);
    const [col] = await db
      .insert(schema.collections)
      .values({
        handle: c.handle,
        title: isCategory ? CATEGORY_COLLECTIONS[c.handle] : titleCase(c.title),
        descriptionHtml: c.descriptionHtml,
        group: isCategory ? "category" : "edit",
        imageUrl: EDIT_IMAGES[c.handle] ?? first?.images[0]?.url ?? null,
        position: pos++,
        seoTitle: `${isCategory ? CATEGORY_COLLECTIONS[c.handle] : titleCase(c.title)} | Trumee`,
      })
      .returning({ id: schema.collections.id });
    const members = c.products.map((h, i) => ({ collectionId: col.id, productId: idByOldHandle.get(h)!, position: i }));
    if (members.length) await db.insert(schema.collectionProducts).values(members.filter((m) => m.productId));
  }

  // Bestsellers from the old homepage
  const featured = [
    "misty-rose-pink-sleeveless-top-with-crochet-lace-and-schiffli-embroidery",
    "mustard-embroidered-cotton-slub-dress-with-balloon-sleeves",
    "checkered-yoke-denim-shirt-with-roll-up-sleeves",
    "vibrant-abstract-dress-with-gathered-slim-fit-details",
    "floral-crochet-lace-up-boho-top",
    "black-floral-textured-georgette-peplum-top",
    "boho-crochet-accent-square-neck-top",
    "scarlet-cotton-net-lace-waist-panel-top",
  ];
  for (const h of featured) {
    const id = idByOldHandle.get(h);
    if (id) await db.update(schema.products).set({ featured: true }).where(sql`id = ${id}`);
  }

  // 2026 collection → draft products (need price, sizes and description before publishing)
  for (const d of catalog.drafts) {
    const [prod] = await db
      .insert(schema.products)
      .values({
        handle: d.handle,
        title: d.title,
        status: "draft",
        productType: d.productType,
        tags: ["2026", "new-arrival", "needs-pricing"],
        options: [{ name: "Size", values: ["XS", "S", "M", "L", "XL"] }],
        descriptionHtml: "<p>Description coming soon.</p>",
      })
      .returning({ id: schema.products.id });
    await db.insert(schema.productImages).values(d.images.map((im, i) => ({ productId: prod.id, ...im, position: i })));
    await db.insert(schema.variants).values(
      ["XS", "S", "M", "L", "XL"].map((s, i) => ({ productId: prod.id, title: s, option1: s, price: 0, inventoryQty: 0, position: i })),
    );
  }

  // Pages
  const pageRows: { handle: string; title: string; bodyHtml: string; seoDescription?: string }[] = catalog.pages.map((p) => ({
    handle: p.handle,
    title: p.title,
    bodyHtml: p.handle === "about-us" ? ABOUT_HTML.trim() : p.bodyHtml,
  }));
  pageRows.push({ handle: "faqs", title: "Frequently Asked Questions", bodyHtml: FAQ_HTML.trim(), seoDescription: "Answers on Trumee orders, payments, COD, delivery times, returns & exchanges, sizing and account questions — all in one place." } as (typeof pageRows)[number]);
  await db.insert(schema.pages).values(pageRows);

  // Blog
  const covers = ["/images/lifestyle/lake-rust.webp", "/images/lifestyle/cafe-chair.webp", "/images/lifestyle/pink-stairs.webp"];
  await db.insert(schema.blogPosts).values(
    catalog.posts.map((p, i) => ({
      handle: p.handle,
      title: p.title,
      excerpt: p.excerpt,
      bodyHtml: p.bodyHtml,
      author: p.author,
      coverUrl: covers[i % covers.length],
      publishedAt: new Date(p.publishedAt),
      tags: ["style guide"],
    })),
  );

  redirectRows.push({ fromPath: "/collections/home", toPath: "/collections/all" });
  if (redirectRows.length) await db.insert(schema.redirects).values(redirectRows).onConflictDoNothing();

  console.log(
    `Imported ${catalog.products.length} products, ${catalog.drafts.length} drafts, ${catalog.collections.length - 1} collections, ` +
      `${pageRows.length} pages, ${catalog.posts.length} posts, ${redirectRows.length} redirects.`,
  );
}

async function ensureOwner() {
  const email = process.env.ADMIN_EMAIL;
  const password = process.env.ADMIN_PASSWORD;
  if (!email || !password) return console.warn("ADMIN_EMAIL / ADMIN_PASSWORD not set — no admin created.");
  const existing = await db.query.staff.findFirst({ where: (s, { eq }) => eq(s.email, email) });
  if (existing) return console.log(`Admin ${email} already exists.`);
  await db.insert(schema.staff).values({
    email,
    name: "Store Owner",
    role: "owner",
    passwordHash: await bcrypt.hash(password, 11),
  });
  console.log(`Created owner account ${email} (password from ADMIN_PASSWORD in .env).`);
}

function titleCase(s: string) {
  return s
    .toLowerCase()
    .replace(/\b(\w)/g, (m) => m.toUpperCase())
    .replace(/\bX\b/g, "x");
}

function guessFabric(text: string) {
  const t = text.toLowerCase();
  for (const f of ["georgette", "rayon", "cotton slub", "cotton flex", "cotton moss", "denim", "viscose", "cotton"]) {
    if (t.includes(f)) return f.replace(/\b\w/g, (m) => m.toUpperCase());
  }
  return null;
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
